example:
  # Server configuration
  title: Mango Demo
  description: This is a demo Mango API
  version: 1.0.0
  port: 8080

  # Matrix of binaries to build
  build:
    platforms:
      # - os: darwin
      #   arch: arm64
      - os: linux
        arch: amd64
      # - os: linux
      #   arch: arm64
      # - os: windows
      #   arch: amd64

  # GRPC/REST API configuration
  api:
    servers:
      - name: localhost
        url: http://localhost:5500/api/
      - name: dev
        url: http://dev/api/

  # Database configuration
  db:
    # engine: sqlite
    # url: mango.dev.db
    engine: postgresql
    url: postgres://postgres:password@localhost:5432/mangodb
