[phases.setup]
nixPkgs = ["devenv", "cachix"]

[phases.install]
cmds = [
  "cachix use go-web-server",
  "devenv shell mango generate"
]
cacheDirectories = []

[phases.build]
cmds = [
  "devenv shell mango build"
]

[start]
    cmd = "./dist/example/example-linux-amd64"
    runImage = 'gcr.io/distroless/static-debian12'
    onlyIncludeFiles = ['./dist/example/']