version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mangodb
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  db_web:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mangodb?sslmode=disable
    depends_on:
      - db
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis:/var/lib/redis

volumes:
  postgres:
  redis:
