root = "."
testdata_dir = "testdata"
tmp_dir = "gen"

[build]
  args_bin = []
  bin = "./gen/dev-build"
  cmd = "generate && go build -o ./gen/dev-build ./main.go"
  delay = 50
  exclude_dir = ["config", "static", "gen", ".devenv", "dist"]
  exclude_file = []
  exclude_regex = ["_templ.go", "_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "proto"]
  include_file = []
  kill_delay = "0s"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  log = "dev-build.log"
  rerun = false
  rerun_delay = 50
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 5550
  enabled = true
  proxy_port = 5500

[screen]
  clear_on_rebuild = false
  keep_scroll = true
