name: Test Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: bufbuild/buf-setup-action@v1
  #       with:
  #         version: "1.32.1"
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: cachix/install-nix-action@v27
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: cachix/cachix-action@v15
  #       with:
  #         name: go-web-server
  #         authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
  #     - name: Install devenv.sh
  #       run: nix profile install nixpkgs#devenv
  #     - name: prepare the project
  #       run: devenv shell
  #     - name: build the project
  #       shell: devenv shell bash -- -e {0}
  #       run: |
  #         mango build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.32.1"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/install-nix-action@v27
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: go-web-server
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Lint the project
        shell: devenv shell bash -- -e {0}
        run: |
          mango generate
          mango lint
